apiVersion: v1
kind: ConfigMap
metadata:
  name: jenish-config
  namespace: sample-app-namespace-1785590340050
  labels:
    app.kubernetes.io/name: jenish
    kubernetes.azure.com/generator: devhub
data: