apiVersion: v1
kind: ConfigMap
metadata:
  name: hiiiii-config
  namespace: namespace-workflow-1785592215351
  labels:
    app.kubernetes.io/name: hiiiii
    kubernetes.azure.com/generator: devhub
data: