apiVersion: v1
kind: ConfigMap
metadata:
  name: temp1-config
  namespace: sample-app-namespace-1786336060083
  labels:
    app.kubernetes.io/name: temp1
    kubernetes.azure.com/generator: devhub
data: