apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temp-deploy
  labels:
    app.kubernetes.io/name: temp-deploy
    app.kubernetes.io/part-of: temp-deploy-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: temp-deploy