apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jenish
  labels:
    app.kubernetes.io/name: jenish
    app.kubernetes.io/part-of: jenish-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: jenish