apiVersion: v1
kind: Service
metadata:
  name: temp
  namespace: namespace-workflow-1785584638371
  labels:
    app.kubernetes.io/name: temp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: temp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080