apiVersion: v1
kind: Service
metadata:
  name: hiiiii
  namespace: namespace-workflow-1785592215351
  labels:
    app.kubernetes.io/name: hiiiii
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hiiiii
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080