name: temp-deploy

on:
  push:
    branches:
      - sport-api
  workflow_dispatch:

env:
  ACR_RESOURCE_GROUP: RGJenishSakhiya
  AZURE_CONTAINER_REGISTRY: containerregistrytemp
  CONTAINER_NAME: image
  CLUSTER_NAME: KuberCluster
  CLUSTER_RESOURCE_GROUP: RGJenishSakhiya
  CLUSTER_RESOURCE_TYPE: Microsoft.ContainerService/managedClusters
  DEPLOYMENT_MANIFEST_PATH: ./.github/workflows/manifests
  DOCKER_FILE: ./Dockerfile
  BUILD_CONTEXT_PATH: ./
  NAMESPACE: sample-app-namespace-1785563152438
  ENABLENAMESPACECREATION: false
  AUTH_TYPE: SERVICE_PRINCIPAL

jobs:
  buildImage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build Docker Image
        run: |
          docker build \
          -f ${{ env.DOCKER_FILE }} \
          -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} \
          .

      - name: Push Docker Image
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy:
    needs: buildImage

    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Install kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.0.25

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: false
          use-kubelogin: true
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}

      - name: Check if AKS is Private
        id: isPrivate
        run: |
          result=$(az aks show \
            --resource-group ${{ env.CLUSTER_RESOURCE_GROUP }} \
            --name ${{ env.CLUSTER_NAME }} \
            --query "apiServerAccessProfile.enablePrivateCluster" \
            -o tsv)

          echo "PRIVATE_CLUSTER=$result" >> $GITHUB_OUTPUT

      - name: Validate Namespace
        run: |
          kubectl get namespace ${{ env.NAMESPACE }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          name: ${{ env.CLUSTER_NAME }}
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}
          private-cluster: ${{ steps.isPrivate.outputs.PRIVATE_CLUSTER == 'true' }}
